<a href="https://colab.research.google.com/github/terra2n/2025_KB_TI-1C/blob/main/KB_Jobsheet_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Tipe Data Python

a. Cek Tipe Data

In [ ]:
>>> var = 123
>>> print(type(var))

<class 'int'>


b. Tipe data String

In [ ]:
>>> a = '123'
>>> b = '3.4'
>>> c = "Data String"
>>> print(type(c))

<class 'str'>


c. Tipe data numerik

In [ ]:
>>> var1 = 345
>>> var2 = 34.5
>>> f1 = float(var1)
>>> print(type(f1))
>>> print(f1)
345.0
>>> sum = var1 + var2
>>> print(sum)
379.5
>>> var3 = 12.3
>>> var4 = 12.9
>>> i1 = int(var2)
>>> i2 = int(var3)
>>> print(i1)
34
>>> print(i2)
12

<class 'float'>
345.0
379.5
34
12


12

d. Tipe Data Boolean

In [ ]:
>>> print(var1 == var2)
False
>>> print(var1 < var2)
False
>>> print(var1 > var2)
True
>>> print(var1 != var2)
True

False
False
True
True


True

e. Tipe Data List

In [ ]:
>>> list = ["belajar dasar python", 2023, 3.8, True]
>>> print(list)
['belajar dasar python', 2023, 3.8, True]
>>> print(list[3])
True
>>> print(list[1:3])
[2023, 3.8]
>>> print(len(list))


['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4


# 2. Operasi matematika menggunakan python

a. Mendapatkan nilai minimum dam maksimum

In [ ]:
x = min(5, 10, 25)
y = max(6, 12, 18)
print(x)
print (y)

5
18


b. Mendapatkan nilai absolut

In [ ]:
x = abs(-7.25)
print (x)

7.25


c. Mendapatkan nilai pangkat

In [ ]:
import math
x = math.pow(4, 3)
print (x)

64.0


d. Mendapatkan nilai akar

In [ ]:
import math
x = math.sqrt(64)
print (x)

8.0


e. Mendapatkan nilai pembulatan

In [ ]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print (x)
print (y)

2
1


f. Mendaptkan nilai konstanta (PI)

In [ ]:
import math
x = math.pi
print (x)

3.141592653589793


# 3. Menggunakan Fungsi MATH

In [ ]:
import math

# Fungsi Trigonometri
angle_rad = math.pi / 4  # 45 derajat dalam radian

print("Fungsi Trigonometri:")
print(f"  Sinus dari {angle_rad} radian: {math.sin(angle_rad)}")  # Menghitung sinus
print(f"  Cosinus dari {angle_rad} radian: {math.cos(angle_rad)}") # Menghitung cosinus
print(f"  Tangen dari {angle_rad} radian: {math.tan(angle_rad)}")  # Menghitung tangen
print("\n")  # Menambahkan baris baru untuk pemisahan

# Fungsi Logaritma
number = 10

print("Fungsi Logaritma:")
print(f"  Logaritma natural dari {number}: {math.log(number)}")   # Menghitung logaritma natural
print(f"  Logaritma basis-10 dari {number}: {math.log10(number)}") # Menghitung logaritma basis-10
print("\n")

# Konversi Sudut
print("Konversi Sudut:")
print(f"  {angle_rad} radian sama dengan {math.degrees(angle_rad)} derajat") # Mengubah radian ke derajat
print("\n")

# Perhitungan Jarak
point1 = (1, 2, 3)
point2 = (4, 5, 6)

print("Perhitungan Jarak:")
print(f"  Jarak antara {point1} dan {point2}: {math.dist(point1, point2)}") # Menghitung jarak Euclidean
print("\n")

# Fungsi Matematika Lainnya
number = 5
numerator = 10
denominator = 3
value = float('nan')

print("Fungsi Matematika Lainnya:")
print(f"  Faktorial dari {number}: {math.factorial(number)}") # Menghitung faktorial
print(f"  Sisa bagi dari {numerator} dibagi {denominator}: {math.fmod(numerator, denominator)}") # Menghitung sisa bagi
print(f"  Apakah {value} NaN? {math.isnan(value)}")  # Memeriksa apakah nilai NaN
print(f"  Gamma dari {number}: {math.gamma(number)}") # Menghitung fungsi gamma

Fungsi Trigonometri:
  Sinus dari 0.7853981633974483 radian: 0.7071067811865475
  Cosinus dari 0.7853981633974483 radian: 0.7071067811865476
  Tangen dari 0.7853981633974483 radian: 0.9999999999999999


Fungsi Logaritma:
  Logaritma natural dari 10: 2.302585092994046
  Logaritma basis-10 dari 10: 1.0


Konversi Sudut:
  0.7853981633974483 radian sama dengan 45.0 derajat


Perhitungan Jarak:
  Jarak antara (1, 2, 3) dan (4, 5, 6): 5.196152422706632


Fungsi Matematika Lainnya:
  Faktorial dari 5: 120
  Sisa bagi dari 10 dibagi 3: 1.0
  Apakah nan NaN? True
  Gamma dari 5: 24.0


# 4. Operasai matriks dan vektor dengan python

a. Membuat matriks di python

In [ ]:
import numpy as np
A = np.array([[80, 30, 25],
[50, 20, 10]])
B = np.array([[30, 60, 15],
[10, 30, 30]])

hasil = A + B
print(hasil)

[[110  90  40]
 [ 60  50  40]]


b. Melakukan operasi do product

In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)
print(hasil)

2025


c. Melakukan operasi cross product

In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

Hasil = np.cross(A, B)
print(Hasil)

[-305 -110  350]


# Tugas Praktikum

In [ ]:
import numpy as np

# Definisikan matriks A, B, dan C
A = np.array([[3, 1], [2, 0]])
B = np.array([[2, 1], [1, -1]])
C = np.array([[-1, 1, 2], [2, 0, -1]])

# Hitung perkalian matriks A x B
hasil_AxB = np.dot(A, B)

# Hitung perkalian matriks B x C
hasil_BxC = np.dot(B, C)

# Tampilkan hasil
print("a. Hasil A x B:")
print(hasil_AxB)

print("\nb. Hasil B x C:")
print(hasil_BxC)

a. Hasil A x B:
[[7 2]
 [4 2]]

b. Hasil B x C:
[[ 0  2  3]
 [-3  1  3]]


In [ ]:
import math

# a. 6!
faktorial_6 = math.factorial(6)
print(f"6! = {faktorial_6}")

# b. 8! / 5!
faktorial_8 = math.factorial(8)
faktorial_5 = math.factorial(5)
hasil_bagi = faktorial_8 / faktorial_5
print(f"8! / 5! = {hasil_bagi}")

6! = 720
8! / 5! = 336.0


In [ ]:
import numpy as np

# Definisikan vektor A dan B
A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

# Hitung panjang vektor A dan B
panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

# Hitung perkalian titik (dot product) A.B
dot_product = np.dot(A, B)

# Hitung perkalian silang (cross product) AxB
cross_product = np.cross(A, B)

# Tampilkan hasil
print("Panjang Vektor A:", panjang_A)
print("Panjang Vektor B:", panjang_B)
print("Perkalian Titik A.B:", dot_product)
print("Perkalian Silang AxB:", cross_product)

Panjang Vektor A: 9.1104335791443
Panjang Vektor B: 12.409673645990857
Perkalian Titik A.B: 58
Perkalian Silang AxB: [ 24  79 -51]
